[project]
name = "portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "python-dotenv>=1.1.0",
    "streamlit>=1.44.1",
    "streamlit-folium>=0.25.0",
]
